export const keys = {
  ACCESS_TOKEN_KEY: 'access-token',
  REFRESH_TOKEN_KEY: 'refresh-token',
  USER_INFO_KEY: 'user-info',
  USER_ROLES_KEY: 'user-roles',
  USER_ACTIVITY_KEY: 'user-activity',
  USER_CONFIG_THEME_COLOR_KEY: 'user-config-theme-color',
  USER_RECIPIENT_KEY: 'user-recipient',
  USER_INFO_PRESCRIPE_BRAND: 'prescripe-brand',
  USER_INFO_PRESCRIPE_COVER: 'prescripe-cover',
  USER_INFO_INSURANCE_COVER: 'insurance-cover',
  USER_LOGIN_DEFAULT_TYPE: 'login-default-type',
  APP_VERSION_KEY: 'app-version',
  TEMPORARY_VISIT_HISTORY: 'temporary-visits',
}
